org.gradle.warning.mode=all

projectVersion=1.12.2

springBootVersion=4.1.0

theJavaVersion=25

versionsPluginVersion=0.54.0
grgitPluginVersion=5.3.3

jdaVersion=6.4.2
#see https://oss.sonatype.org/content/repositories/snapshots/com/discord4j/discord4j-core/
d4jCoreVersion=3.3.2

dsProxyVersion=1.11.0
troveVersion=3.0.3
fastutilVersion=8.5.18
