org.gradle.warning.mode=all

projectVersion=1.11.1

springBootVersion=3.5.10

javaVersion=21

versionsPluginVersion=0.53.0
grgitPluginVersion=5.3.3

jdaVersion=6.3.0
#see https://oss.sonatype.org/content/repositories/snapshots/com/discord4j/discord4j-core/
d4jCoreVersion=3.3.0

dsProxyVersion=1.11.0
troveVersion=3.0.3
fastutilVersion=8.5.18
