name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7
        with:
          fetch-depth: 0

      - name: Gradle Wrapper Verification
        uses: gradle/actions/wrapper-validation@dbbdc275be76ac10734476cc723d82dfe7ec6eda # 3.4.2

      - name: Setup JDK
        uses: actions/setup-java@99b8673ff64fbf99d8d325f52d9a5bdedb8483e9 # v4.2.1
        with:
          distribution: "temurin"
          java-version: 21
          cache: "gradle"

      - name: Print JDK info
        run: java -Xmx32m --version

      - name: Gradle Build
        uses: burrunan/gradle-cache-action@a54b6ce2cbbba932e5d142129dddef103e6ad143 # v1.19
        with:
          arguments: build --info
