name: Build

on: push

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # v3.1.0
        with:
          fetch-depth: 0

      - name: Gradle Wrapper Verification
        uses: gradle/wrapper-validation-action@55e685c48d84285a5b0418cd094606e199cca3b6 # v1.0.5

      - name: Setup JDK
        uses: actions/setup-java@de1bb2b0c5634f0fc4438d7aa9944e68f9bf86cc # v3.6.0
        with:
          distribution: "temurin"
          java-version: 17
          cache: "gradle"

      - name: Print JDK info
        run: java -Xmx32m --version

      - name: Gradle Build
        uses: burrunan/gradle-cache-action@5424817e64ccb6bf267f715f5a46de1bf777c633 # v1.12
        with:
          arguments: build --info
